### ISSUE TITLE
Integrate ipld-eth-statedb

### ISSUE THREAD

**Issue by i-norden** [vulcanize/ipld-eth-db-validator#28]
Adjust ipld-eth-db-validator to perform state transitions using ipld-eth-statedb

This provides a means of validating the data in the `state_cids` and `storage_cids` table.

I think we want to continue to perform the state transition using ipfs-ethdb as well, comparing all three results: expected result from levelDB, result obtained by performing state transition on our db using ipld-eth-statedb, result obtained by performing state transition on our db using ipfs-ethdb.

**Comment by roysc** [comment]
Ultimately this didn't work, since our ipld-eth-statedb `direct-by-leaf` DB is read only and the validator requires full read-write operations to perform EVM state transitions. Instead I've implemented it in https://github.com/cerc-io/ipld-eth-db-validator/pull/32 using the new Trie impl in https://github.com/cerc-io/ipld-eth-statedb/pull/19.

**Comment by i-norden** [comment]
@roysc could we make a read-write version of the `direct-by-leaf`? Neither are actually writing back to the underlying DB.

**Comment by roysc** [comment]
We could, but we would have to build the trie from the final data to get the commitment hash. But if this is done entirely in memory, I am guessing it would still outperform ipfs-ethdb (`trie-by-cid`). It should also be somewhat parallelizable.

**Comment by i-norden** [comment]
Thanks for that context, that makes sense and isn't a priority for now.
